# Generated by Django 3.2.1 on 2021-06-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='scheme',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
