# Generated by Django 3.2.1 on 2021-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='typ',
            field=models.CharField(choices=[('فعل', 'فعل'), ('اسم', 'اسم'), ('اسم/نعت', 'اسم/نعت')], max_length=100, null=True),
        ),
    ]
