# Generated by Django 3.2 on 2021-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='prenom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
