# Generated by Django 3.2.1 on 2021-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Persones',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
