# Generated by Django 3.2.1 on 2021-06-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210614_1429'),
    ]

    operations = [
    ]
