# Generated by Django 3.2 on 2021-06-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210614_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racine',
            old_name='id',
            new_name='id_rac',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='id',
            new_name='id_sch',
        ),
    ]
