# Generated by Django 3.2.1 on 2021-06-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210515_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racine',
            fields=[
                ('id_rac', models.BigAutoField(primary_key=True, serialize=False)),
                ('rac', models.CharField(max_length=30)),
                ('type_rac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id_sch', models.BigAutoField(primary_key=True, serialize=False)),
                ('sch_cons', models.CharField(max_length=30)),
                ('sch_voy', models.CharField(max_length=30)),
                ('type_scheme', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verbe',
            fields=[
                ('id_ver', models.BigAutoField(primary_key=True, serialize=False)),
                ('ver_cons', models.CharField(max_length=30)),
                ('ver_voy', models.CharField(max_length=30)),
                ('racine_ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.racine')),
                ('scheme_ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Nom',
            fields=[
                ('id_nom', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_cons', models.CharField(max_length=30)),
                ('nom_voy', models.CharField(max_length=30)),
                ('racine_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.racine')),
                ('scheme_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.scheme')),
            ],
        ),
    ]
