# Generated by Django 3.2.1 on 2021-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_nom_racine_scheme_verbe'),
    ]

    operations = [
        migrations.AddField(
            model_name='nom',
            name='nom',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='verbe',
            name='verbe',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
